apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: weave-scope-probe
  labels:
    daemonset: weave-scope-probe
    heritage: helm
spec:
  template:
    metadata:
      name:  weave-scope-probe
      labels:
        daemonset: weave-scope-probe
        heritage: helm
    spec:
      containers:
      - name:  weave-scope-probe
        image: weaveworks/scope:0.11.1
        command:
        - "--no-app"
        - "--probe.docker"
        - "true"
        - "--probe.docker.bridge"
        - "docker0" # change this in case the Docker bridge is named `cbr0` in your system
        - "--probe.kubernetes"
        - "true"
        - "weave-scope-app"
        hostPID: true
        hostIPC: true
        hostNetwork: true
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 50m
        volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
