apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  labels:
    provider: weave-scope-app
    heritage: helm
spec:
  ports:
  - name: weave-scope-app-port
    port: 4040
  selector:
    provider: weave-scope-app
